dataset:
  path: "data/bronze"  
  file: "spam.csv"

synonym_aug_params:
  sources: 'wordnet' # wordnet or ppdb but ppdb needs downloads that are not in the code 
  aug_p: 0.3
  aug_min: 1
  aug_max: 5


spelling_aug_params:
  aug_p: 0.3
  aug_min: 1
  aug_max: 5


oversample_factors: 1.25
# agreed range of study = 1.25, 1.5, 2.0 
  
experiment_name: "spam-classifier"
experiment_description: "This experiment contains mlruns for different approaches in the ml lifecycle of an e-mail spam detector classifier."
experiment_tags:
  project_name: "NLP-text-classifier"
  project_stage: "testing"
  team: "ml-team"
  project_quarter: "Q4-2024"


experiment_defaults:
  dataset: "Spam detection"
  task: "classification"
  framework: "Scikit-learn"
  language: "Python"
  environment: "Local"
  dataset_version: "0.1.0"
  preprocessing_version: "0.1.0"
  model_version: "0.1.0"
  developer: "Mldu"
  project_stage: "testing"

