dataset:
  path: "data/bronze"  
  file: "dataset.csv" 

synonym_aug:
  sources:
    - wordnet
    - ppdb
  aug_p: 
    min: 0.3
    max: 0.8
  aug_min: 1
  aug_max: 
    min: 5
    max: 10

  
experiment_name: "spam-classifier"
experiment_description: "This experiment contains mlruns for different approaches in the ml lifecycle of an e-mail spam detector classifier."
experiment_tags:
  project_name: "NLP-text-classifier"
  project_stage: "testing"
  team: "ml-team"
  project_quarter: "Q4-2024"


experiment_defaults:
  dataset: "Spam detection"
  task: "classification"
  framework: "Scikit-learn"
  language: "Python"
  environment: "Local"
  dataset_version: "0.1.0"
  preprocessing_version: "0.1.0"
  model_version: "0.1.0"
  developer: "Mldu"
  project_stage: "testing"

