name: Execute Experimentation Notebooks
on:
  push:
    branches:
      - main

jobs:
  execute-notebooks:
    runs-on: ubuntu-latest
    env: #set to true if you want to run the experiment 
      baseline_model: "false" 
      textaug_KeyboardAug_bow_MNB: "false"
      textaug_AntonymAug_bow_MNB: "true"
      textaug_SpellingAug_bow_MNB: "true"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'



    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
        poetry install

    - name: Execute baseline_model if set to true
      run: |
        if [ "$baseline_model" = "true" ]; then
        cd research/02_baseline_model && pwd
        poetry run papermill ./baseline_model.ipynb ./baseline_model.ipynb --kernel python3
        echo "baseline_model executed successfully"
        else
            echo "Skipping baseline_model execution"
          fi
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}


    - name: Execute textaug_KeyboardAug_bow_MNB if set to true
      run: |
        if [ "$textaug_KeyboardAug_bow_MNB" = "true" ]; then
        cd research/03_text_augmentation && pwd
        poetry run papermill ./textaug_KeyboardAug_bow_MNB.ipynb ./textaug_KeyboardAug_bow_MNB.ipynb --kernel python3
        echo "textaug_KeyboardAug_bow_MNB executed successfully"
        else
            echo "Skipping textaug_KeyboardAug_bow_MNB execution"
          fi
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}


    - name: Execute textaug_AntonymAug_bow_MNB if set to true
      run: |
        if [ "$textaug_AntonymAug_bow_MNB" = "true" ]; then
        cd research/03_text_augmentation && pwd
        poetry run papermill ./textaug_AntonymAug_bow_MNB.ipynb ./textaug_AntonymAug_bow_MNB.ipynb --kernel python3
        echo "textaug_AntonymAug_bow_MNB executed successfully"
        else
            echo "Skipping textaug_AntonymAug_bow_MNB execution"
          fi
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}


    - name: Execute textaug_SpellingAug_bow_MNB if set to true
      run: |
        if [ "$textaug_SpellingAug_bow_MNB" = "true" ]; then
        cd research/03_text_augmentation && pwd
        poetry run papermill ./textaug_SpellingAug_bow_MNB.ipynb ./textaug_SpellingAug_bow_MNB.ipynb --kernel python3
        echo "textaug_SpellingAug_bow_MNB executed successfully"
        else
            echo "Skipping textaug_SpellingAug_bow_MNB execution"
          fi
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}


  






