name: SageMaker Training with GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  sagemaker:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Checkout code
      uses: actions/checkout@v2


    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - name: Install dependencies with Poetry
      run: |
        poetry install


    - name: Install AWS CLI and Papermill
      run: |
        pip install awscli papermill boto3

    - name: Create S3 folders for results
      run: |
        aws s3api put-object --bucket mlflow-spam-detection-artifacts --key baseline_model/notebooks/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-east-1'

    - name: Upload Jupyter Notebook to S3
      run: |
        aws s3 cp 02_baseline_model.ipynb s3://mlflow-spam-detection-artifacts/baseline_model/notebooks/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-east-1'

    - name: Execute Jupyter Notebook in SageMaker
      run: |
        papermill s3://mlflow-spam-detection-artifacts/baseline_model/notebooks/02_baseline_model.ipynb \
                  s3://mlflow-spam-detection-artifacts/baseline_model/notebooks/02_baseline_model_trained.ipynb
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-east-1'

