name: Manual Trigger to Train Notebook + register on Mlflow

on:
  push:
    branches:
      - main

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
        poetry install

    - name: Execute Jupyter Notebook
      run: |
        cd research/02_baseline_model
        #NOTE - Remember to change the name of the notebook file here in future iterations
        notebook_file="baseline_model.ipynb"  
        poetry run papermill ./$notebook_file ./$notebook_file --kernel python3 -p NOTEBOOK_NAME=$notebook_file
        echo "Notebook executed successfully"


    - name: Run MLflow Tracking
      run: |
        python -m mlflow run .
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'
